"""create applications table

Revision ID: 5c6dd5b62690
Revises: 
Create Date: 2026-07-29 12:18:19.223687
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c6dd5b62690'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'rejected', 'deleted', name='applicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('group_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_telegram_user_id'), ['telegram_user_id'], unique=False)
        batch_op.create_index('ix_applications_visible', ['deleted_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_visible')
        batch_op.drop_index(batch_op.f('ix_applications_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_category'))

    op.drop_table('applications')
    # ### end Alembic commands ###
