"""make license_plate unique

Revision ID: 72e5921670ed
Revises: b1a9300dc911
Create Date: 2026-08-04 14:10:53.780816
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72e5921670ed'
down_revision: Union[str, None] = 'b1a9300dc911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_trailer_license_plate', ['license_plate'])

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_truck_license_plate', ['license_plate'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_constraint('uq_truck_license_plate', type_='unique')

    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trailer_license_plate', type_='unique')

    # ### end Alembic commands ###
