"""add trips

Revision ID: e551df298167
Revises: 72e5921670ed
Create Date: 2026-08-05 13:46:21.897290
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e551df298167'
down_revision: Union[str, None] = '72e5921670ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ttn_num', sa.Text(), nullable=False),
    sa.Column('arrival_date', sa.Text(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('exporter_company_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('logist_fullname', sa.Text(), nullable=False),
    sa.Column('logist_phone_number', sa.Text(), nullable=False),
    sa.Column('logist_tg', sa.BigInteger(), nullable=False),
    sa.Column('truck', sa.Text(), nullable=False),
    sa.Column('truck_license_plate', sa.Text(), nullable=False),
    sa.Column('trailer', sa.Text(), nullable=False),
    sa.Column('trailer_type', sa.Text(), nullable=False),
    sa.Column('trailer_license_plate', sa.Text(), nullable=False),
    sa.Column('grain_type', sa.Text(), nullable=False),
    sa.Column('driver_fullname', sa.Text(), nullable=False),
    sa.Column('driver_phone_number', sa.Text(), nullable=False),
    sa.Column('datetime_entry', sa.Text(), nullable=True),
    sa.Column('datetime_departure', sa.Text(), nullable=True),
    sa.Column('b_mass', sa.Integer(), server_default='0', nullable=False),
    sa.Column('t_mass', sa.Integer(), server_default='0', nullable=False),
    sa.Column('n_mass', sa.Integer(), server_default='0', nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['exporter_company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index('ix_trips_client', ['client_company_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_ttn_num'), ['ttn_num'], unique=False)
        batch_op.create_index('ix_trips_visible', ['deleted_at', 'arrival_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index('ix_trips_visible')
        batch_op.drop_index(batch_op.f('ix_trips_ttn_num'))
        batch_op.drop_index('ix_trips_client')

    op.drop_table('trips')
    # ### end Alembic commands ###
